#![crate_name = "iw"]
#![crate_type = "lib"]

pub mod act1;
pub mod agent;
pub mod assets;
pub mod config;
pub mod def;
pub mod draw;
pub mod fixed;
pub mod game;
pub mod input;
pub mod play;
pub mod time;
pub mod scale;
pub mod user;
pub mod util;
pub mod vga_render;
pub mod vl;