name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Update
        run: |
          sudo apt-get update
          sudo apt-get install -y \
                      just libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Test All
        run: just test-all
