name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toochain: stable
    - name: Update
      run: sudo apt-get update
    - name: Install SDL
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
